"use client";
import {useEffect,useMemo,useState} from "react";

type Pkg=Record<string,any>;
const money=(n:number,c="CNY")=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:c||"CNY",maximumFractionDigits:2}).format(n||0);
const today=()=>new Date().toISOString().slice(0,10);
const iso=(date:string,end=false)=>`${date} ${end?"23:59:59":"00:00:00"}`;

export default function Home(){
 const [orders,setOrders]=useState<Pkg[]>([]),[date,setDate]=useState(today()),[shop,setShop]=useState("all"),[status,setStatus]=useState("all"),[query,setQuery]=useState("");
 const [syncing,setSyncing]=useState(false),[message,setMessage]=useState("尚未同步"),[lastSync,setLastSync]=useState("");
 useEffect(()=>{try{setOrders(JSON.parse(localStorage.getItem("miaoshou-orders")||"[]"));setLastSync(localStorage.getItem("miaoshou-last-sync")||"")}catch{}},[]);
 const normalized=useMemo(()=>orders.map((p:any)=>{const o=p.orderInfo||{};return {...p,_id:String(o.platformOrderSn||p.platformPackageNo||p.appPackageNo||o.opOrderId||Math.random()),_shop:String(p.shopName||p.shopNick||p.shopId||"未知店铺"),_shopId:String(p.shopId||o.shopId||""),_platform:String(p.platformName||p.platform||o.platform||"未知平台"),_amount:Number(o.payAmount??o.orderAmount??0),_currency:String(o.currency||"CNY"),_status:String(p.appPackageStatusText||o.appOrderStatusText||p.platformPackageStatus||o.platformOrderStatus||"未知状态"),_time:String(o.gmtOrderStart||o.gmtPay||o.gmtOrderModified||""),_items:Array.isArray(p.items)?p.items:[]}}),[orders]);
 const shops=useMemo(()=>Array.from(new Set(normalized.map(o=>o._shop))).sort(),[normalized]);
 const shown=useMemo(()=>normalized.filter(o=>(shop==="all"||o._shop===shop)&&(status==="all"||o._status.includes(status))&&(!query||(o._id+o._shop+o._platform+o._items.map((i:any)=>i.title).join("")).toLowerCase().includes(query.toLowerCase()))&&(!o._time||o._time.slice(0,10)===date)),[normalized,shop,status,query,date]);
 const sales=shown.reduce((n,o)=>n+o._amount,0),refunds=shown.filter(o=>/退|cancel|refund/i.test(o._status)).reduce((n,o)=>n+o._amount,0);
 async function sync(){setSyncing(true);setMessage("正在读取妙手订单…");try{const res=await fetch("/api/miaoshou/sync",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({page:1,pageSize:100,modifiedFrom:iso(date),modifiedTo:iso(date,true)})});const data=await res.json();if(!res.ok||!data.ok)throw new Error(data.message||"同步失败");const byId=new Map(orders.map((x:any)=>[String(x.orderInfo?.platformOrderSn||x.platformPackageNo||x.appPackageNo),x]));for(const x of data.packages||[])byId.set(String(x.orderInfo?.platformOrderSn||x.platformPackageNo||x.appPackageNo),x);const next=Array.from(byId.values());setOrders(next);const time=new Date().toLocaleString("zh-CN");setLastSync(time);setMessage(`同步完成，本次读取 ${data.count} 条`);localStorage.setItem("miaoshou-orders",JSON.stringify(next));localStorage.setItem("miaoshou-last-sync",time)}catch(e){setMessage(e instanceof Error?e.message:"同步失败")}finally{setSyncing(false)}}
 return <div className="app"><aside><div className="logo"><b>单</b><span>订单日记<small>妙手多店铺</small></span></div><nav><a className="active">总览</a><a>订单</a><a>店铺</a><a>同步记录</a></nav><div className="connection"><i className={lastSync?"ok":""}/><div><b>{lastSync?"妙手已连接":"等待连接"}</b><small>{lastSync?`上次 ${lastSync}`:"填写密钥后同步"}</small></div></div></aside>
 <main><header><div><p className="eyebrow">DAILY ORDER DESK</p><h1>多店铺订单总览</h1><p>把妙手里的订单集中到一个清楚的页面。</p></div><button className="sync" onClick={sync} disabled={syncing}>{syncing?"同步中…":"↻ 立即同步"}</button></header>
 <section className="notice"><span>{message}</span><small>数据只显示在当前浏览器；下一步可增加云端保存。</small></section>
 <section className="stats"><Card label="订单数量" value={String(shown.length)} note="当前筛选结果"/><Card label="销售金额" value={money(sales,shown[0]?._currency)} note="实付金额合计"/><Card label="退款金额" value={money(refunds,shown[0]?._currency)} note="退款或取消订单"/><Card label="店铺数量" value={String(shops.length)} note="已同步店铺"/></section>
 <section className="panel"><div className="toolbar"><div><h2>订单列表</h2><p>按日期、店铺和状态查看</p></div><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><select value={shop} onChange={e=>setShop(e.target.value)}><option value="all">全部店铺</option>{shops.map(s=><option key={s}>{s}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option><option>待发货</option><option>已发货</option><option>已完成</option><option>退款</option><option>取消</option></select><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索订单号、店铺或商品"/></div>
 <div className="table"><div className="thead"><span>订单</span><span>店铺</span><span>商品</span><span>状态</span><span>实付金额</span></div>{shown.length?shown.map(o=><div className="row" key={o._id}><span><b>{o._id}</b><small>{o._time||"—"}</small></span><span><b>{o._shop}</b><small>{o._platform}</small></span><span><b>{o._items[0]?.title||"订单商品"}</b><small>{o._items.length?`${o._items.length}种商品`:"暂无明细"}</small></span><span><em>{o._status}</em></span><span className="price">{money(o._amount,o._currency)}</span></div>):<div className="empty"><b>还没有订单数据</b><span>填写妙手密钥后，点击“立即同步”。</span></div>}</div></section>
 </main></div>
}
function Card({label,value,note}:{label:string,value:string,note:string}){return <article><p>{label}</p><strong>{value}</strong><small>{note}</small></article>}
