"use client";
import {useEffect,useMemo,useState} from "react";

type Pkg=Record<string,any>;
const money=(n:number,c="CNY")=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:c||"CNY",maximumFractionDigits:2}).format(n||0);
const today=()=>new Date().toISOString().slice(0,10);
const iso=(date:string,end=false)=>`${date} ${end?"23:59:59":"00:00:00"}`;

export default function Home(){
 const [view,setView]=useState("overview");
 const [orders,setOrders]=useState<Pkg[]>([]),[date,setDate]=useState(today()),[shop,setShop]=useState("all"),[status,setStatus]=useState("all"),[query,setQuery]=useState("");
 const [syncing,setSyncing]=useState(false),[message,setMessage]=useState("尚未同步"),[lastSync,setLastSync]=useState("");
 const [trendDays,setTrendDays]=useState(7);
 useEffect(()=>{try{setOrders(JSON.parse(localStorage.getItem("miaoshou-orders")||"[]"));setLastSync(localStorage.getItem("miaoshou-last-sync")||"")}catch{}},[]);
 const normalized=useMemo(()=>orders.map((p:any)=>{const o=p.orderInfo||{};return {...p,_id:String(o.platformOrderSn||p.platformPackageNo||p.appPackageNo||o.opOrderId||Math.random()),_shop:String(p.shopName||p.shopNick||p.shopId||"未知店铺"),_shopId:String(p.shopId||o.shopId||""),_platform:String(p.platformName||p.platform||o.platform||"未知平台"),_amount:Number(o.payAmount??o.orderAmount??0),_currency:String(o.currency||"CNY"),_status:String(p.appPackageStatusText||o.appOrderStatusText||p.platformPackageStatus||o.platformOrderStatus||"未知状态"),_time:String(o.gmtOrderStart||o.gmtPay||o.gmtOrderModified||""),_items:Array.isArray(p.items)?p.items:[]}}),[orders]);
 const shops=useMemo(()=>Array.from(new Set(normalized.map(o=>o._shop))).sort(),[normalized]);
 const shown=useMemo(()=>normalized.filter(o=>(shop==="all"||o._shop===shop)&&(status==="all"||o._status.includes(status))&&(!query||(o._id+o._shop+o._platform+o._items.map((i:any)=>i.title).join("")).toLowerCase().includes(query.toLowerCase()))&&(!o._time||o._time.slice(0,10)===date)),[normalized,shop,status,query,date]);
 const sales=shown.reduce((n,o)=>n+o._amount,0),refunds=shown.filter(o=>/退|cancel|refund/i.test(o._status)).reduce((n,o)=>n+o._amount,0);
 const trend=useMemo(()=>Array.from({length:trendDays},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(trendDays-1-i));const key=d.toISOString().slice(0,10);const list=normalized.filter(o=>o._time?.slice(0,10)===key);return {date:key.slice(5).replace("-","/"),count:list.length,sales:list.reduce((n,o)=>n+o._amount,0)}}),[normalized,trendDays]);
 async function sync(){setSyncing(true);setMessage("正在读取妙手订单…");try{const res=await fetch("/api/miaoshou/sync",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({page:1,pageSize:100,modifiedFrom:iso(date),modifiedTo:iso(date,true)})});const data=await res.json();if(!res.ok||!data.ok)throw new Error(data.message||"同步失败");const byId=new Map(orders.map((x:any)=>[String(x.orderInfo?.platformOrderSn||x.platformPackageNo||x.appPackageNo),x]));for(const x of data.packages||[])byId.set(String(x.orderInfo?.platformOrderSn||x.platformPackageNo||x.appPackageNo),x);const next=Array.from(byId.values());setOrders(next);const time=new Date().toLocaleString("zh-CN");setLastSync(time);setMessage(`同步完成，本次读取 ${data.count} 条`);localStorage.setItem("miaoshou-orders",JSON.stringify(next));localStorage.setItem("miaoshou-last-sync",time)}catch(e){setMessage(e instanceof Error?e.message:"同步失败")}finally{setSyncing(false)}}
 const go=(next:string)=>{setView(next);const selector=next==="orders"?".panel":next==="shops"?".stats":next==="history"?".notice":"header";setTimeout(()=>document.querySelector(selector)?.scrollIntoView({behavior:"smooth"}),0)};
 return <div className="app"><aside><div className="logo"><b>单</b><span>订单日记<small>妙手多店铺</small></span></div><nav><button className={view==="overview"?"active":""} onClick={()=>go("overview")}>总览</button><button className={view==="orders"?"active":""} onClick={()=>go("orders")}>订单</button><button className={view==="shops"?"active":""} onClick={()=>go("shops")}>店铺</button><button className={view==="history"?"active":""} onClick={()=>go("history")}>同步记录</button></nav><div className="connection"><i className={lastSync?"ok":""}/><div><b>{lastSync?"妙手已连接":"等待连接"}</b><small>{lastSync?`上次 ${lastSync}`:"填写密钥后同步"}</small></div></div></aside>
 <main><header><div><p className="eyebrow">DAILY ORDER DESK</p><h1>多店铺订单总览</h1><p>把妙手里的订单集中到一个清楚的页面。</p></div><button className="sync" onClick={sync} disabled={syncing}>{syncing?"同步中…":"↻ 立即同步"}</button></header>
 <section className={`notice ${view==="history"?"highlight":""}`}><span>{view==="history"?"最近一次同步：":""}{message}</span><small>{view==="history"&&lastSync?`同步时间：${lastSync}`:"数据只显示在当前浏览器；下一步可增加云端保存。"}</small></section>
 <section className={`stats ${view==="shops"?"highlight":""}`}><Card label="订单数量" value={String(shown.length)} note="当前筛选结果"/><Card label="销售金额" value={money(sales,shown[0]?._currency)} note="实付金额合计"/><Card label="退款金额" value={money(refunds,shown[0]?._currency)} note="退款或取消订单"/><Card label="店铺数量" value={String(shops.length)} note={view==="shops"?(shops.join("、")||"暂无店铺"):"已同步店铺"}/></section>
 {view==="overview"&&<TrendChart data={trend} days={trendDays} onDays={setTrendDays}/>} 
 <section className="panel"><div className="toolbar"><div><h2>订单列表</h2><p>按日期、店铺和状态查看</p></div><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><select value={shop} onChange={e=>setShop(e.target.value)}><option value="all">全部店铺</option>{shops.map(s=><option key={s}>{s}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option><option>待发货</option><option>已发货</option><option>已完成</option><option>退款</option><option>取消</option></select><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索订单号、店铺或商品"/></div>
 <div className="table"><div className="thead"><span>订单</span><span>店铺</span><span>商品</span><span>状态</span><span>实付金额</span></div>{shown.length?shown.map(o=><div className="row" key={o._id}><span><b>{o._id}</b><small>{o._time||"—"}</small></span><span><b>{o._shop}</b><small>{o._platform}</small></span><span><b>{o._items[0]?.title||"订单商品"}</b><small>{o._items.length?`${o._items.length}种商品`:"暂无明细"}</small></span><span><em>{o._status}</em></span><span className="price">{money(o._amount,o._currency)}</span></div>):<div className="empty"><b>还没有订单数据</b><span>填写妙手密钥后，点击“立即同步”。</span></div>}</div></section>
 </main></div>
}
function Card({label,value,note}:{label:string,value:string,note:string}){return <article><p>{label}</p><strong>{value}</strong><small>{note}</small></article>}
function TrendChart({data,days,onDays}:{data:{date:string;count:number;sales:number}[];days:number;onDays:(n:number)=>void}){
 const width=900,height=250,pad=38,maxCount=Math.max(1,...data.map(d=>d.count)),maxSales=Math.max(1,...data.map(d=>d.sales));
 const points=(key:"count"|"sales",max:number)=>data.map((d,i)=>`${pad+i*(width-pad*2)/Math.max(1,data.length-1)},${height-pad-(d[key]/max)*(height-pad*2)}`).join(" ");
 return <section className="trend-card"><div className="trend-head"><div><h2>订单趋势</h2><p>根据已经同步的真实订单自动统计</p></div><div><button className={days===7?"active":""} onClick={()=>onDays(7)}>近7天</button><button className={days===30?"active":""} onClick={()=>onDays(30)}>近30天</button></div></div><div className="legend"><span className="blue">订单量</span><span className="orange">销售金额</span></div><div className="chart-wrap"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="订单趋势曲线图">{[0,1,2,3,4].map(i=><line key={i} x1={pad} x2={width-pad} y1={pad+i*(height-pad*2)/4} y2={pad+i*(height-pad*2)/4} className="grid-line"/>)}<polyline points={points("sales",maxSales)} className="line sales-line"/><polyline points={points("count",maxCount)} className="line count-line"/>{data.map((d,i)=>{const x=pad+i*(width-pad*2)/Math.max(1,data.length-1);return <g key={d.date}><circle cx={x} cy={height-pad-(d.count/maxCount)*(height-pad*2)} r="4" className="count-dot"><title>{d.date}：{d.count}单</title></circle>{(days===7||i%5===0||i===data.length-1)&&<text x={x} y={height-10} textAnchor="middle">{d.date}</text>}</g>})}</svg></div><div className="trend-summary"><span>最高单量 <b>{maxCount} 单</b></span><span>最高销售额 <b>{money(maxSales)}</b></span><small>没有曲线数据时，请先选择相应日期并点击“立即同步”</small></div></section>
}
